---
name: Build production container
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-22.04
    name: Docker Push
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build . -t metacpan/metacpan-api-v0-shim:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push build to Docker Hub
        run: docker push metacpan/metacpan-api-v0-shim:latest
