---
name: Build deployment container
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-22.04
    name: Docker Push
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ github.repository }}:test
          target: test
          push: false
      - name: Run Perl tests
        run: docker run -i ${{ github.repository }}:test
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Docker meta (sha)
        id: docker-sha-tag
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
      - if: contains( fromJSON(steps.meta.outputs.json).tags, "${{ github.repository }}:latest")
        run: echo 'need update to ${{ steps.docker-sha-tag.outputs.tags }}'
